// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from "./client";
import { client } from "./client.gen";
import type {
  CreateBookingData,
  CreateBookingErrors,
  CreateBookingResponses,
  CreateHotelData,
  CreateHotelResponses,
  DeleteBookingData,
  DeleteBookingResponses,
  DeleteHotelData,
  DeleteHotelResponses,
  GetBookingByIdData,
  GetBookingByIdResponses,
  GetBookingsData,
  GetBookingsResponses,
  GetHotelByIdData,
  GetHotelByIdErrors,
  GetHotelByIdResponses,
  GetHotelsData,
  GetHotelsResponses,
  LoginData,
  LoginErrors,
  LoginResponses,
  UpdateBookingData,
  UpdateBookingResponses,
  UpdateHotelData,
  UpdateHotelResponses,
} from "./types.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Get all hotels
 */
export const getHotels = <ThrowOnError extends boolean = false>(
  options: Options<GetHotelsData, ThrowOnError>,
) =>
  (options.client ?? client).get<GetHotelsResponses, unknown, ThrowOnError>({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/hotels",
    ...options,
  });

/**
 * Create a new hotel
 */
export const createHotel = <ThrowOnError extends boolean = false>(
  options: Options<CreateHotelData, ThrowOnError>,
) =>
  (options.client ?? client).post<CreateHotelResponses, unknown, ThrowOnError>({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/hotels",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Delete a hotel
 */
export const deleteHotel = <ThrowOnError extends boolean = false>(
  options: Options<DeleteHotelData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    DeleteHotelResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/hotels/{id}",
    ...options,
  });

/**
 * Get a hotel by ID
 */
export const getHotelById = <ThrowOnError extends boolean = false>(
  options: Options<GetHotelByIdData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetHotelByIdResponses,
    GetHotelByIdErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/hotels/{id}",
    ...options,
  });

/**
 * Update a hotel
 */
export const updateHotel = <ThrowOnError extends boolean = false>(
  options: Options<UpdateHotelData, ThrowOnError>,
) =>
  (options.client ?? client).put<UpdateHotelResponses, unknown, ThrowOnError>({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/hotels/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get all bookings
 */
export const getBookings = <ThrowOnError extends boolean = false>(
  options: Options<GetBookingsData, ThrowOnError>,
) =>
  (options.client ?? client).get<GetBookingsResponses, unknown, ThrowOnError>({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/bookings",
    ...options,
  });

/**
 * Create a new booking
 */
export const createBooking = <ThrowOnError extends boolean = false>(
  options: Options<CreateBookingData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    CreateBookingResponses,
    CreateBookingErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/bookings",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Delete a booking
 */
export const deleteBooking = <ThrowOnError extends boolean = false>(
  options: Options<DeleteBookingData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    DeleteBookingResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/bookings/{id}",
    ...options,
  });

/**
 * Get a booking by ID
 */
export const getBookingById = <ThrowOnError extends boolean = false>(
  options: Options<GetBookingByIdData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetBookingByIdResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/bookings/{id}",
    ...options,
  });

/**
 * Update a booking
 */
export const updateBooking = <ThrowOnError extends boolean = false>(
  options: Options<UpdateBookingData, ThrowOnError>,
) =>
  (options.client ?? client).put<UpdateBookingResponses, unknown, ThrowOnError>(
    {
      security: [{ scheme: "bearer", type: "http" }],
      url: "/bookings/{id}",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    },
  );

/**
 * Authenticate user
 */
export const login = <ThrowOnError extends boolean = false>(
  options: Options<LoginData, ThrowOnError>,
) =>
  (options.client ?? client).post<LoginResponses, LoginErrors, ThrowOnError>({
    url: "/auth/login",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
