// This file is auto-generated by @hey-api/openapi-ts

import { z } from "zod";

export const zHotelStatus = z.enum(["active", "maintenance", "closed"]);

export const zHotelUpsert = z.object({
  name: z.string().min(1),
  location: z.string(),
  status: zHotelStatus,
});

export const zHotel = zHotelUpsert.and(
  z.object({
    id: z.uuid(),
    createdAt: z.iso.datetime(),
  }),
);

export const zBookingStatus = z.enum(["pending", "confirmed", "cancelled"]);

export const zBookingUpsert = z.object({
  hotelId: z.uuid(),
  checkInDate: z.iso.date(),
  checkOutDate: z.iso.date(),
  status: zBookingStatus,
});

export const zBooking = zBookingUpsert.and(
  z.object({
    id: z.uuid(),
    bookingNumber: z.string(),
    createdAt: z.iso.datetime(),
  }),
);

export const zLoginRequest = z.object({
  email: z.email(),
  password: z.string().min(1),
});

export const zLoginResponse = z.object({
  accessToken: z.string(),
  user: z.object({
    id: z.uuid(),
    email: z.email(),
  }),
});

export const zPaginatedResponse = z.object({
  totalItems: z.int(),
  totalPages: z.int(),
  currentPage: z.int(),
  pageSize: z.int(),
});

export const zBookingList = zPaginatedResponse.and(
  z.object({
    items: z.array(zBooking),
  }),
);

export const zError = z.object({
  code: z.int(),
  message: z.string(),
});

export const zValidationError = z.object({
  errors: z.record(z.string(), z.string()),
});

export const zGetHotelsData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.object({
    page: z.int().gte(1),
    pageSize: z.int().gte(1),
    status: z.optional(zHotelStatus),
  }),
});

/**
 * A paginated list of hotels
 */
export const zGetHotelsResponse = zPaginatedResponse.and(
  z.object({
    items: z.array(zHotel),
  }),
);

export const zCreateHotelData = z.object({
  body: zHotelUpsert,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * Hotel created
 */
export const zCreateHotelResponse = zHotel;

export const zDeleteHotelData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    id: z.uuid(),
  }),
  query: z.optional(z.never()),
});

/**
 * Hotel deleted
 */
export const zDeleteHotelResponse = z.void();

export const zGetHotelByIdData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    id: z.uuid(),
  }),
  query: z.optional(z.never()),
});

/**
 * Hotel details
 */
export const zGetHotelByIdResponse = zHotel;

export const zUpdateHotelData = z.object({
  body: zHotelUpsert,
  path: z.object({
    id: z.uuid(),
  }),
  query: z.optional(z.never()),
});

/**
 * Hotel updated
 */
export const zUpdateHotelResponse = zHotel;

export const zGetBookingsData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.object({
    page: z.int().gte(1),
    pageSize: z.int().gte(1),
  }),
});

/**
 * A paginated list of bookings
 */
export const zGetBookingsResponse = zBookingList;

export const zCreateBookingData = z.object({
  body: zBookingUpsert,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * Booking created
 */
export const zCreateBookingResponse = zBooking;

export const zDeleteBookingData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    id: z.uuid(),
  }),
  query: z.optional(z.never()),
});

/**
 * Booking deleted
 */
export const zDeleteBookingResponse = z.void();

export const zGetBookingByIdData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    id: z.uuid(),
  }),
  query: z.optional(z.never()),
});

/**
 * Booking details
 */
export const zGetBookingByIdResponse = zBooking;

export const zUpdateBookingData = z.object({
  body: zBookingUpsert,
  path: z.object({
    id: z.uuid(),
  }),
  query: z.optional(z.never()),
});

/**
 * Booking updated
 */
export const zUpdateBookingResponse = zBooking;

export const zLoginData = z.object({
  body: zLoginRequest,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * User authenticated
 */
export const zLoginResponse2 = zLoginResponse;
