// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: "http://localhost:3000" | (string & {});
};

export type Hotel = HotelUpsert & {
  id: string;
  createdAt: string;
};

export type HotelUpsert = {
  name: string;
  /**
   * Location on Mars
   */
  location: string;
  status: HotelStatus;
};

export type HotelStatus = "active" | "maintenance" | "closed";

export type Booking = BookingUpsert & {
  id: string;
  bookingNumber: string;
  createdAt: string;
};

export type BookingUpsert = {
  hotelId: string;
  checkInDate: string;
  checkOutDate: string;
  status: BookingStatus;
};

export type BookingStatus = "pending" | "confirmed" | "cancelled";

export type BookingList = PaginatedResponse & {
  items: Array<Booking>;
};

export type LoginRequest = {
  email: string;
  password: string;
};

export type LoginResponse = {
  accessToken: string;
  user: {
    id: string;
    email: string;
  };
};

export type PaginatedResponse = {
  totalItems: number;
  totalPages: number;
  currentPage: number;
  pageSize: number;
};

export type _Error = {
  code: number;
  message: string;
};

export type ValidationError = {
  errors: {
    [key: string]: string;
  };
};

export type GetHotelsData = {
  body?: never;
  path?: never;
  query: {
    page: number;
    pageSize: number;
    status?: HotelStatus;
  };
  url: "/hotels";
};

export type GetHotelsResponses = {
  /**
   * A paginated list of hotels
   */
  200: PaginatedResponse & {
    items: Array<Hotel>;
  };
};

export type GetHotelsResponse = GetHotelsResponses[keyof GetHotelsResponses];

export type CreateHotelData = {
  body: HotelUpsert;
  path?: never;
  query?: never;
  url: "/hotels";
};

export type CreateHotelResponses = {
  /**
   * Hotel created
   */
  201: Hotel;
};

export type CreateHotelResponse =
  CreateHotelResponses[keyof CreateHotelResponses];

export type DeleteHotelData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/hotels/{id}";
};

export type DeleteHotelResponses = {
  /**
   * Hotel deleted
   */
  204: void;
};

export type DeleteHotelResponse =
  DeleteHotelResponses[keyof DeleteHotelResponses];

export type GetHotelByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/hotels/{id}";
};

export type GetHotelByIdErrors = {
  /**
   * Hotel not found
   */
  404: _Error;
};

export type GetHotelByIdError = GetHotelByIdErrors[keyof GetHotelByIdErrors];

export type GetHotelByIdResponses = {
  /**
   * Hotel details
   */
  200: Hotel;
};

export type GetHotelByIdResponse =
  GetHotelByIdResponses[keyof GetHotelByIdResponses];

export type UpdateHotelData = {
  body: HotelUpsert;
  path: {
    id: string;
  };
  query?: never;
  url: "/hotels/{id}";
};

export type UpdateHotelResponses = {
  /**
   * Hotel updated
   */
  200: Hotel;
};

export type UpdateHotelResponse =
  UpdateHotelResponses[keyof UpdateHotelResponses];

export type GetBookingsData = {
  body?: never;
  path?: never;
  query: {
    page: number;
    pageSize: number;
  };
  url: "/bookings";
};

export type GetBookingsResponses = {
  /**
   * A paginated list of bookings
   */
  200: BookingList;
};

export type GetBookingsResponse =
  GetBookingsResponses[keyof GetBookingsResponses];

export type CreateBookingData = {
  body: BookingUpsert;
  path?: never;
  query?: never;
  url: "/bookings";
};

export type CreateBookingErrors = {
  /**
   * Invalid booking data
   */
  400: ValidationError | _Error;
};

export type CreateBookingError = CreateBookingErrors[keyof CreateBookingErrors];

export type CreateBookingResponses = {
  /**
   * Booking created
   */
  201: Booking;
};

export type CreateBookingResponse =
  CreateBookingResponses[keyof CreateBookingResponses];

export type DeleteBookingData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/bookings/{id}";
};

export type DeleteBookingResponses = {
  /**
   * Booking deleted
   */
  204: void;
};

export type DeleteBookingResponse =
  DeleteBookingResponses[keyof DeleteBookingResponses];

export type GetBookingByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/bookings/{id}";
};

export type GetBookingByIdResponses = {
  /**
   * Booking details
   */
  200: Booking;
};

export type GetBookingByIdResponse =
  GetBookingByIdResponses[keyof GetBookingByIdResponses];

export type UpdateBookingData = {
  body: BookingUpsert;
  path: {
    id: string;
  };
  query?: never;
  url: "/bookings/{id}";
};

export type UpdateBookingResponses = {
  /**
   * Booking updated
   */
  200: Booking;
};

export type UpdateBookingResponse =
  UpdateBookingResponses[keyof UpdateBookingResponses];

export type LoginData = {
  body: LoginRequest;
  path?: never;
  query?: never;
  url: "/auth/login";
};

export type LoginErrors = {
  /**
   * Invalid credentials
   */
  401: _Error;
};

export type LoginError = LoginErrors[keyof LoginErrors];

export type LoginResponses = {
  /**
   * User authenticated
   */
  200: LoginResponse;
};

export type LoginResponse2 = LoginResponses[keyof LoginResponses];
